import React, { useState } from 'react';
import { UploadedImage, RegistrationMetrics, MatchPoint } from '../types';
import { Download, FileJson, FileSpreadsheet, FileText, Check } from 'lucide-react';

interface DownloadButtonsProps {
  referenceImage: UploadedImage;
  sourceImage: UploadedImage;
  registeredImageUrl: string;
  metrics: RegistrationMetrics;
  matchPoints: MatchPoint[];
}

export const DownloadButtons: React.FC<DownloadButtonsProps> = ({
  referenceImage,
  sourceImage,
  registeredImageUrl,
  metrics,
  matchPoints,
}) => {
  const [downloadSuccess, setDownloadSuccess] = useState<string | null>(null);

  const notifySuccess = (type: string) => {
    setDownloadSuccess(type);
    setTimeout(() => setDownloadSuccess(null), 2500);
  };

  // Download Registered Image
  const handleDownloadImage = () => {
    const link = document.createElement('a');
    link.download = `LUNARIS_REGISTERED_${referenceImage.sensor}_${sourceImage.sensor}_${Date.now()}.png`;
    link.href = registeredImageUrl;
    link.click();
    notifySuccess('image');
  };

  // Export Match Points JSON
  const handleExportJson = () => {
    const exportData = {
      mission: 'ISRO Chandrayaan-2 Lunar Image Registration',
      timestamp: new Date().toISOString(),
      sensors: {
        reference: referenceImage.sensor,
        source: sourceImage.sensor,
      },
      metrics: {
        rmsePx: metrics.rmse,
        totalMatches: metrics.totalMatches,
        inliers: metrics.inliers,
        inlierRatioPct: metrics.inlierRatio,
        transformation: metrics.transformation,
      },
      matchPoints: matchPoints.map((pt) => ({
        id: pt.id,
        refNormalized: [Number(pt.x1.toFixed(5)), Number(pt.y1.toFixed(5))],
        srcNormalized: [Number(pt.x2.toFixed(5)), Number(pt.y2.toFixed(5))],
        inlier: pt.inlier,
        confidence: Number(pt.confidence.toFixed(4)),
        subpixelOffset: pt.subpixelOffset,
      })),
      disclaimer: 'Prototype Demonstration Data — Generated by LUNARIS Web Prototype',
    };

    const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.download = `LUNARIS_MATCH_POINTS_${Date.now()}.json`;
    link.href = url;
    link.click();
    URL.revokeObjectURL(url);
    notifySuccess('json');
  };

  // Export Match Points CSV
  const handleExportCsv = () => {
    const headers = ['PointID', 'Ref_X_Norm', 'Ref_Y_Norm', 'Src_X_Norm', 'Src_Y_Norm', 'IsInlier', 'Confidence', 'SubpixelDx', 'SubpixelDy'];
    const rows = matchPoints.map((pt) => [
      pt.id,
      pt.x1.toFixed(5),
      pt.y1.toFixed(5),
      pt.x2.toFixed(5),
      pt.y2.toFixed(5),
      pt.inlier ? '1' : '0',
      pt.confidence.toFixed(4),
      pt.subpixelOffset[0].toFixed(4),
      pt.subpixelOffset[1].toFixed(4),
    ]);

    const csvContent = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.download = `LUNARIS_CORRESPONDENCE_${Date.now()}.csv`;
    link.href = url;
    link.click();
    URL.revokeObjectURL(url);
    notifySuccess('csv');
  };

  // Export Mission Analysis Report Text
  const handleExportReport = () => {
    const reportText = `================================================================================
LUNARIS: LUNAR IMAGE REGISTRATION & CORRESPONDENCE ANALYSIS REPORT
ISRO Chandrayaan-2 Multi-Modal Optical Registration Engine
================================================================================
Report Date: ${new Date().toISOString()}
Session ID: #LUN-${Date.now().toString().slice(-6)}
Status: ${metrics.status}

1. MISSION OBSERVATION CONFIGURATION
--------------------------------------------------------------------------------
Reference Sensor:  ${referenceImage.sensor} (Orbiter High Resolution Camera)
Reference Image:   ${referenceImage.name} (${referenceImage.width}x${referenceImage.height} px)
Target Region:     ${referenceImage.targetRegion || 'Lunar South Pole / Shackleton'}

Source Sensor:     ${sourceImage.sensor} (Terrain Mapping Camera-2 / IIRS)
Source Image:      ${sourceImage.name} (${sourceImage.width}x${sourceImage.height} px)

2. REGISTRATION TELEMETRY METRICS
--------------------------------------------------------------------------------
Root Mean Square Error (RMSE):   ${metrics.rmse.toFixed(2)} px  [Target: < 1.0 px]
Total Match Candidates:          ${metrics.totalMatches} points
Verified Spatial Inliers:        ${metrics.inliers} points
Inlier Ratio:                    ${metrics.inlierRatio.toFixed(2)}%
Sub-pixel Precision:             ${metrics.subpixelPrecision} px
Execution Time:                  ${(metrics.processingTimeMs / 1000).toFixed(2)} s

3. ESTIMATED GEOMETRIC TRANSFORMATION
--------------------------------------------------------------------------------
Planar Rotation:                 ${metrics.transformation.rotationDeg.toFixed(2)} deg
Scale Factor:                    ${metrics.transformation.scaleFactor.toFixed(2)}x
Translation Vector:              [X: ${metrics.transformation.translationX.toFixed(2)} px, Y: ${metrics.transformation.translationY.toFixed(2)} px]

Homography Matrix (3x3):
[ ${metrics.transformation.homography[0].map(n => n.toFixed(4)).join('  ')} ]
[ ${metrics.transformation.homography[1].map(n => n.toFixed(4)).join('  ')} ]
[ ${metrics.transformation.homography[2].map(n => n.toFixed(4)).join('  ')} ]

================================================================================
* DISCLAIMER: Prototype Demonstration Metrics generated for visual demonstration.
================================================================================
`;

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.download = `LUNARIS_MISSION_REPORT_${Date.now()}.txt`;
    link.href = url;
    link.click();
    URL.revokeObjectURL(url);
    notifySuccess('report');
  };

  return (
    <div className="bg-[#0B1220] border border-slate-800 rounded-2xl p-5 space-y-4 shadow-xl backdrop-blur-md">
      <div className="flex items-center justify-between border-b border-slate-800 pb-3">
        <div className="flex items-center gap-2">
          <Download className="w-4 h-4 text-[#35C6F4]" />
          <span className="text-xs font-bold font-mono text-slate-200 tracking-wider">
            MISSION DATA EXPORT &amp; ARTIFACTS
          </span>
        </div>
        {downloadSuccess && (
          <span className="text-[11px] font-mono text-[#35D07F] flex items-center gap-1">
            <Check className="w-3 h-3" /> Exported {downloadSuccess.toUpperCase()}
          </span>
        )}
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
        
        {/* Button 1: Download Image */}
        <button
          type="button"
          id="download-registered-img-btn"
          onClick={handleDownloadImage}
          className="flex items-center justify-center gap-2 px-4 py-3 rounded-xl bg-gradient-to-r from-[#35C6F4]/20 to-[#7C8CFF]/20 border border-[#35C6F4]/40 hover:border-[#35C6F4] text-xs font-mono font-semibold text-slate-200 hover:text-white transition-all shadow-md group glow-cyan-sm"
        >
          <Download className="w-4 h-4 text-[#35C6F4] group-hover:translate-y-0.5 transition-transform" />
          <span>↓ Registered Image (.PNG)</span>
        </button>

        {/* Button 2: Export JSON */}
        <button
          type="button"
          id="export-match-json-btn"
          onClick={handleExportJson}
          className="flex items-center justify-center gap-2 px-4 py-3 rounded-xl bg-[#050812] border border-slate-800 hover:border-slate-700 text-xs font-mono font-medium text-slate-300 hover:text-white transition-all"
        >
          <FileJson className="w-4 h-4 text-[#7C8CFF]" />
          <span>Export Matches (.JSON)</span>
        </button>

        {/* Button 3: Export CSV */}
        <button
          type="button"
          id="export-match-csv-btn"
          onClick={handleExportCsv}
          className="flex items-center justify-center gap-2 px-4 py-3 rounded-xl bg-[#050812] border border-slate-800 hover:border-slate-700 text-xs font-mono font-medium text-slate-300 hover:text-white transition-all"
        >
          <FileSpreadsheet className="w-4 h-4 text-[#35D07F]" />
          <span>Match Points (.CSV)</span>
        </button>

        {/* Button 4: Export Mission Report */}
        <button
          type="button"
          id="export-mission-report-btn"
          onClick={handleExportReport}
          className="flex items-center justify-center gap-2 px-4 py-3 rounded-xl bg-[#050812] border border-slate-800 hover:border-slate-700 text-xs font-mono font-medium text-slate-300 hover:text-white transition-all"
        >
          <FileText className="w-4 h-4 text-[#F5B942]" />
          <span>Mission Report (.TXT)</span>
        </button>

      </div>
    </div>
  );
};
